# Generated by Django 4.0.4 on 2022-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Secondname',
            field=models.CharField(blank=True, help_text='Введите отчество ребенка', max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Выберите родителей ребенка', null=True, to='mainapp.parent', verbose_name='Родители'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director',
            field=models.CharField(blank=True, help_text='Введите директора организации', max_length=150, null=True, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='section',
            name='coach',
            field=models.CharField(blank=True, help_text='Введите главного тренера секции', max_length=150, null=True, verbose_name='Тренер'),
        ),
    ]
