# Generated by Django 4.0.4 on 2022-05-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_child_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garten',
            name='number',
        ),
        migrations.AlterField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Выберите родителей ребенка', to='mainapp.parent', verbose_name='Родители'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Выберите секции ребенка', to='mainapp.section', verbose_name='Секции'),
        ),
    ]
