# Generated by Django 4.0.4 on 2022-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_garten_number_alter_child_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garten',
            name='number',
            field=models.IntegerField(default=1, help_text='Введите номер детского сада', verbose_name='Номер дет. сада'),
        ),
    ]
