# Generated by Django 4.0.4 on 2022-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_garten_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Введите дату начала', verbose_name='Дата'),
        ),
    ]
